module.exports = {
  BID_ASKING: 'BID_ASKING',
  BID_OFFERING: 'BID_OFFERING',
  BID_RESULT: 'BID_RESULT',
  HEALTH: 'HEALTH',

  TASK_DONE: 'TASK_DONE',
  TASK_ASSIGNING: 'TASK_ASSIGNING',
  TASK_REWARD: 'TASK_REWARD',
}
